### PR TITLE
build(node-version): raised the minimum required node-version to v14

### PR DESCRIPTION
**Pull request by mikearche**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I wanted to update `svgo` because in sdc we are getting warnings from one of it's dependencies. In order to update `svgo` we need to use Node 14, and in order to upgrade to Node 14 this project needed to update husky.

**Fixes:** #143 and #111 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

There are a lot of changes in this project, but they mostly have to do with `package.json` changes as well as husky pre-commit changes. I wanted to do the work to clean up the dependencies as much as possible, because as I said above I would love to update svgo.

I pinned the unreleased package `@web/dev-server` in case there is a version release that causes things to break.

I removed `@semantic-release/npm` because I noticed that it was already a dependency of @semantic-release.

I also updated `@semantic-release` as well as it's dependencies to the latest version since we can do that now that we only support Node 14 or higher.

I'm also following semver, for updating the package version to 5.0.0 because requiring Node 14 or higher is a breaking change.

Useful links:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8

## Type of change:

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by MattSidor** [comment]
@mikearche When you get a chance, can you open a new issue for the `svgo` version warning?

**Comment by mikearche** [comment]
I created an issue @MattSidor #149. I think we can also move it to a `devDependency` while that issue is being fixed as well.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
The following commands need to be run in order for Husky to run the pre-commit scripts. 

```
chmod ug+x .husky/*
chmod ug+x .git/hooks/*
```

**Comment by blackfalcon** [comment]
SEMVER is only needed for customer-facing releases. This update has no effect to a consumer. Build changes are related to the repo and that is managed via Git versioning.

**Comment by blackfalcon** [comment]
Also, we remove the Node 12.x test dependency 

https://github.com/AlaskaAirlines/Icons/blob/master/.github/workflows/testPublish.yml#L18

**Comment by mikearche** [comment]
> 

Interesting, the pre-commit hook is working for me. It could be a windows thing though. I shouldn't have any globally installed dependencies either. It fired off when I amended my commit.

**Comment by mikearche** [comment]
> @mikearche can you add me to this repo? The Husky pre-commit is still not working.
> 
> ```
> hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
> hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
> ```
Interesting, the pre-commit hook is working for me. It could be a windows thing though. I shouldn't have any globally installed dependencies either. It fired off when I amended my commit. I added you to the repo.

**Review by blackfalcon — APPROVED** [review]

**Pull request merged**
