### PR TITLE
feat: adds change planes svg

### PR DESCRIPTION
**Pull request by gusnaughton**
# Alaska Airlines Pull Request

Adds the Change Planes logo

## Type of change:

Please delete options that are not relevant.

- [x] New capability 

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
I (@blackfalcon) reached out to the design team for an assist on how to move forward with this new icon.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
The SVG needs to be cleaned up. Also there is a discussion to be had about how to manage this new type of icon/illustration.

**Comment by blackfalcon** [comment]
Do we have any status updates on this PR?

**Comment by gusnaughton** [comment]
@erikalanghauser would it be possible to export the above SVG following the Auro SVG guidelines? http://auro.alaskaair.com/icons/overview @blackfalcon could you please explain what in the SVG needs to change?

**Comment by blackfalcon** [comment]
> @erikalanghauser would it be possible to export the above SVG following the Auro SVG guidelines? http://auro.alaskaair.com/icons/overview @blackfalcon could you please explain what in the SVG needs to change?

I am not saying anything has to change. What my question is, we have a very specific spec for icons https://auro.alaskaair.com/icons/overview. This was reviewed and approved and all the icons for this spec. 

This new 'icon' does not fit that spec so I have nowhere in the design system to put it. 

When I pressed for an answer prior I was told that this was an 'illustration'. Ok, but we can't simply just start calling things new names when we don't have a spec to fit it to. 

Outside of the physical characteristics of this SVG, is it an icon or an illustration? How am I to integrate this into the design system? 

The Sr UI Designers should have some input in this as well.

**Comment by vidalmenAS** [comment]
@blackfalcon apologies! i know that illustration conversation has stalled a couple of times. This definitely appears to be an outlier when comparing to the standards set for icons. I'll make it a priority to circle back with Suze on getting something more concrete on when and where an illustration like this makes sense and how its distinguished against icons.

In the meantime, I'm okay with this one-off.

**Comment by blackfalcon** [comment]
@vidalmenAS 

> In the meantime, I'm okay with this one-off.

I am not sure what that means? Update this SVG to fit within the standard spec or ... ¯\_(ツ)_/¯

**Comment by gusnaughton** [comment]
not in scope of DS

**Pull request closed without merging**
