### PR TITLE
Update AA tail icon

### PR DESCRIPTION
**Pull request by blackfalcon**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #105 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

This PR replaces the AA tail icon with a less complex SVG. This is a 420KB reduction in size of the icon. 

**BEFORE**
Screen Shot 2022-04-13 at 1 26 52 PM

**AFTER**
Screen Shot 2022-04-13 at 1 25 20 PM

## Type of change:

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by MattSidor — APPROVED** [review]
yay! looks awesome. big improvement.

**Comment by gusnaughton** [comment]
The colors on the new tail are different - has this been approved by Alliances and AA? They tend to be particular about their brand representation on our site. Huge improvement for file size that I'm super excited about!

**Comment by blackfalcon** [comment]
> The colors on the new tail are different - has this been approved by Alliances and AA? They tend to be particular about their brand representation on our site. Huge improvement for file size that I'm super excited about!

This was the version of the icon that was given from design as a version they are using on other UIs.

**Pull request merged**
