### PR TITLE
Feature--new-window-icon

### PR DESCRIPTION
**Pull request by clockeby**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** # (adds new-window.svg and updates icons.json)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

I've added a new file, new-window.svg, for the new window icon to be used with Auro-hyperlink, and updated the src/data/icons.json file with information for the new-window icon.

## Type of change:

- [X] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [X] My update follows the CONTRIBUTING guidelines of this project
- [X] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — CHANGES_REQUESTED** [review]
Please review the cut of the SVG. I feel that it's missing the outer padding. 
https://auro.alaskaair.com/icons/guidelines

**Comment by clockeby** [comment]
Thanks, I'm not sure when/how that was deleted. Possibly while cleaning up the SVG code. Anyway, it's been fixed!

**Comment by blackfalcon** [comment]
> Please review the cut of the SVG. I feel that it's missing the outer padding.
> https://auro.alaskaair.com/icons/guidelines

verified that the icon meets the spec

Screen Shot 2021-03-17 at 4 57 04 PM

**Comment by blackfalcon** [comment]
Admin needs to address issues with the commit log before merging. Please allow me access to your fork.

**Review by blackfalcon — APPROVED** [review]

**Pull request merged**
