### PR TITLE
Add new flight search icons #83

### PR DESCRIPTION
**Pull request by blackfalcon**
# Alaska Airlines Pull Request

**Resolves:** #83 

## Summary:

Adds the following icons:

* src/icons/discount-code-applied.svg
* src/icons/first-class-upgrade-available.svg
* src/icons/first-class-upgrade-waitlist.svg
* src/icons/free-same-day-change.svg
* src/icons/mixed-cabin-itinerary.svg
* src/icons/not-recommended-for-standby.svg
* src/icons/premium-class-upgrade-available.svg
* src/icons/premium-class-upgrade-waitlist.svg
* src/icons/recommended-for-standby-travel-but-monitor.svg
* src/icons/recommended-for-standby.svg
* src/icons/route-pending-government-approval.svg

## Type of change:

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Other (new icons)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
Need new icons for 

* recommended-for-standby-travel-but-monitor.svg
* first-class-upgrade-available.svg
* first-class-upgrade-waitlist.svg

**Comment by blackfalcon** [comment]
@Kaylablyton1 please reply to this message so that I can include you in the review process. Thanks!

**Comment by blackfalcon** [comment]
@KaylaBlyton1 please review this URL to ensure that the delivered new icons are correct. 

https://auro-icons-flight-search-83.surge.sh/

**Comment by blackfalcon** [comment]
@KaylaBlyton1 if there is feedback on the icons, I will wait until that is completed before moving forward with this update. 

This is the icon that is marked for deprecation?
Screen Shot 2021-05-12 at 5 34 02 AM

**Comment by blackfalcon** [comment]
@KaylaBlyton1 what is an ETA on getting the new icons past design review to unblock this PR?

**Comment by blackfalcon** [comment]
@KaylaBlyton1 please let me know as to the status of these updates.

**Comment by blackfalcon** [comment]
#### Icons updated:

Screen Shot 2021-06-15 at 10 47 35 AM

#### Added icons:

@KaylaBlyton1  The following icons also require descriptions before we can release. 

Screen Shot 2021-06-15 at 10 56 37 AM
Screen Shot 2021-06-15 at 10 59 28 AM

**Comment by KaylaBlyton1** [comment]
@blackfalcon Thank you! Here are the descriptions:

contract-fare: A fare rate for companies that have a contract with Alaska Air
contract-mixed-fare: Some segments of this journey include contract fare rates, others do not
government-fare: A fare rate only visible only to government employees
government-mixed-fare: Some segments of this journey include government fare rates, others do not

**Pull request merged**
